name: Android Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on:
  push:
    branches:
      - master

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Run kotlin linter
      - name: Run Kotlin Linter
        run: ./gradlew ktlint

      # Run unit tests
      - name: Run Unit Tests
        run: sudo ./gradlew testDebugUnitTest
      
      # Generate Documentation
      - name: Generate Documentation
        run: sudo ./gradlew dokkaHtml

  build-and-deploy:
      name : Generate and deploy documentation
      runs-on: ubuntu-latest
      steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Run Document Generation
      - name: Generate Document
        run: ./gradlew dokkaHtml
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: app/build/docs # The folder the action should deploy.
   
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: sudo ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
